name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > github-ec2.pem && chmod 600 github-ec2.pem
          ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST} '
            echo "Current directory: $(pwd)"
            echo "Listing home directory:"
            ls -la ~

            echo "Installing Node.js..."
            if ! command -v nvm &> /dev/null; then
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
              export NVM_DIR="$HOME/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            fi
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install node 22

            echo "Installing PM2..."
            if ! command -v pm2 &> /dev/null; then
              npm install -g pm2
            fi

            REPO_URL="https://github.com/n4ryn/be-pair-pro.git"
            BRANCH="main"
            REPO_DIR="$HOME/be-pair-pro"

            if [ -d "$REPO_DIR/.git" ]; then
              cd "$REPO_DIR"
              git pull origin "$BRANCH"
            else
              git clone "$REPO_URL" "$REPO_DIR"
              cd "$REPO_DIR"
            fi

            echo "Installing dependencies..."
            npm install

            echo "Starting/restarting application..."
            pm2 restart 0 || pm2 start npm --name "0" -- start
          '
